### ISSUE TITLE
Multiple animations

### ISSUE THREAD

**Issue by Ebsan** [felixblaschke/sa_stateless_animation#1]
I may have missed it, but is there a way to do multiple animations on a single widget? Is it as easy as stacking a PlayAnimation on top of another PlayAnimation in the builder? I'm attempting to tween the color, size and rotation of an icon. Something like the checkmarks designed here: https://dribbble.com/shots/9501605-Essentials?utm_source=Clipboard_Shot&utm_campaign=imargarita&utm_content=Essentials&utm_medium=Social_Share

**Comment by felixblaschke** [comment]
https://github.com/felixblaschke/sa_multi_tween
